---
engine: knitr
execute:
  eval: false
---

# Acknowledgements {.unnumbered}

### Funding

This work is funded by the [Digital and Data Literacy in Teaching Lab (DDLitLab)](https://www.isa.uni-hamburg.de/en/ddlitlab.html), an initiative by the Center for Interdisciplinary Study Programs (Zentrum für Interdisziplinäre Studienangebote; [ISA-Zentrum](https://www.isa.uni-hamburg.de/)) at the [University of Hamburg](https://www.uni-hamburg.de/en.html), Germany.
The Digital and Data Literacy in Teaching Lab program is in turn funded by the [Stiftung Innovation in der Hochschullehre](https://stiftung-hochschullehre.de/en/) (details about the funding program can be found [here](https://stiftung-hochschullehre.de/projekt/ddlitlab/)).

Our project proposal can be found [here]({{< var links.proposal >}}) (in German).

Special thanks to [Carolin Scharfenberg](https://www.isa.uni-hamburg.de/en/ddlitlab/team/scharfenberg-carolin.html){target="_blank"} as well as [Moritz Kreinsen](https://www.isa.uni-hamburg.de/en/ddlitlab/team/kreinsen-moritz.html) and [Sören-Kristian Berger](https://www.isa.uni-hamburg.de/en/ddlitlab/team/berger-soeren-kristian.html) for help with project coordination, administration, and the grant application process.

### Code

This website is made with 🖤 and [Quarto](https://quarto.org/).
The source code of this website can be found [on GitHub]({{< var project.remote >}}) {{< fa brands github >}}.

### Images

Images are stored on [Nextcloud]({{< var links.nextcloud >}}) (UHH Cloud).
They can be retrieved using 

```{bash}
make download-images
```

<details>
<summary>Click here to view the full `Makefile` of this project.</summary>
```{bash, filename="Makefile"}
#| eval: false
#| file: Makefile
#| code-line-numbers: true
```
</details>

### Analytics

We use [Plausible](https://plausible.io/) for website analytics.
Plausible is an "intuitive, lightweight and open source web analytics", does not use cookies and is fully compliant with GDPR, CCPA and PECR.

### License

All contents are licensed under a Creative Commons Attribution-ShareAlike 4.0 International ([CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)) license, unless indicated otherwise.

### Contact

Did you spot an error?
Is there an issue with the website?
Do you have feedback, questions or comments?
We would love to hear from you!
Please open an [issue on GitHub]({{< var links.issues >}}) or send an [email]({{< var links.email >}}){target="_blank"}.
Thank you!
