---
engine: knitr
execute:
  eval: false
  echo: true
format:
  html:
    code-overflow: scroll
    code-line-numbers: true
---

# Exercises {.unnumbered}

Here is a collection of hands-on exercises to complement the chapters in the Version Control Book.
These exercises can be used flexibly throughout a course about Git but also when you are learning on your own.

## Instructions

You can view the exercises by clicking on the boxes in the individual sections that correspond to one of the chapters.
Try to solve the exercises on your own first before looking at the solutions.
Please note that the solutions do not always implement the tasks exactly, but can also use variations to show that different approaches are possible or so it works automatically.
If you want to start each exercise with a clean repository, you can download the repository of the previous solution as a `.zip` file and start the exercises in this repository.

## Overview

- [Command Line](#command-line)
- [First Steps with Git](#first-steps-with-git)
- [Branches](#branches)
- [GitHub: Intro](#github-intro)
- [GitHub: Advanced](#github-advanced)
- [Tags and Releases](#tags-and-releases)
- [Graphical User Interfaces](#graphical-user-interfaces)
- [Stashing and Co.](#stashing-and-co.)

## Command Line

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-cli.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}

```{zsh filename="Code"}
cd /path/to/your/chosen/directory # <1>
```
1. Navigate into the chosen location.
Replace `/path/to/your/chosen/directory` with a path on your computer.
A good location might be within your `/Documents` folder or a dedicated `/Projects` or `/University` folder.
This can help to easily find course-related files on your computer.

```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-cli.sh
```
{{< include ../exercises/_solutions-cli.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-cli.txt
```
:::

::: {.callout-note title="Variation - Longer version + Solutions" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-cli-long.qmd >}}
:::

[Download the folder](../exercises-repos/recipes-cli.zip){.btn .btn-outline-primary role="button"}

## Setup

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-setup.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-setup.sh
```
{{< include ../exercises/_solutions-setup.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output", echo = seq(4, 18)}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-setup.txt
```
:::

[Download the repository](../exercises-repos/recipes-setup.zip){.btn .btn-outline-primary role="button"}

## First steps with Git

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-first-steps-git.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-first-steps-git.sh
```
{{< include ../exercises/_solutions-first-steps-git.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-first-steps-git.txt
```
:::

[Download the repository](../exercises-repos/recipes-first-steps.zip){.btn .btn-outline-primary role="button"}

### Amend a commit

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-essentials-amend.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-essentials-amend.sh
```
{{< include ../exercises/_solutions-essentials-amend.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-essentials-amend.txt
```
:::

[Download the repository](../exercises-repos/recipes-essentials-amend.zip){.btn .btn-outline-primary role="button"}

### Create a `.gitignore` file

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-essentials-gitignore.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-essentials-gitignore.sh
```
{{< include ../exercises/_solutions-essentials-gitignore.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-essentials-gitignore.txt
```
:::

[Download the repository](../exercises-repos/recipes-essentials-gitignore.zip){.btn .btn-outline-primary role="button"}

## Branches

### Create and merge a new branch

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-branches.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-branches.sh
```
{{< include ../exercises/_solutions-branches.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-branches.txt
```
:::

[Download the repository](../exercises-repos/recipes-branches.zip){.btn .btn-outline-primary role="button"}

### Create and resolve a merge conflict

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-branches-merge-conflict.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-branches-merge-conflict.sh
```
{{< include ../exercises/_solutions-branches-merge-conflict.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-branches-merge-conflict.txt
```
:::

[Download the repository](../exercises-repos/recipes-branches-merge-conflict.zip){.btn .btn-outline-primary role="button"}

## GitHub: Intro

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-github-intro.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
{{< include ../exercises/_solutions-github-intro.qmd >}}
:::

## GitHub: Advanced

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-github-advanced.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
{{< include ../exercises/_solutions-github-advanced.qmd >}}
:::

## Tags and Releases

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-tags-releases.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
{{< include ../exercises/_solutions-tags-releases.qmd >}}
:::

## Graphical User Interfaces

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-gui.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
{{< include ../exercises/_solutions-gui.qmd >}}
:::

## Stashing

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-stashing.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-stashing.sh
```
{{< include ../exercises/_solutions-stashing.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-stashing.txt
```
:::

[Download the repository](../exercises-repos/recipes-stashing.zip){.btn .btn-outline-primary role="button"}

## Reverting

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-reverting.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-reverting.sh
```
{{< include ../exercises/_solutions-reverting.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-reverting.txt
```
:::

[Download the repository](../exercises-repos/recipes-reverting.zip){.btn .btn-outline-primary role="button"}

## Rebasing

::: {.callout-note title="Exercises" collapse="true" appearance="simple"}
{{< include ../exercises/_exercises-rebasing.qmd >}}
:::

::: {.callout-tip title="Solutions" collapse="true" appearance="simple"}
```{zsh, filename="Code"}
#| eval: false
#| file: code/code-exercises-rebasing.sh
```
{{< include ../exercises/_solutions-rebasing.qmd >}}
:::

::: {.callout-tip title="Command history" collapse="true" appearance="simple"}
```{zsh, filename="Output"}
#| code-copy: false
#| eval: false
#| file: exercises-repos/history-rebasing.txt
```
:::

[Download the repository](../exercises-repos/recipes-rebasing.zip){.btn .btn-outline-primary role="button"}

