---
title-block-style: default
---

# Preface {.unnumbered}

## Introduction

Welcome to the world of version control! 
The purpose of this book is to empower scientists, researchers, and students with the knowledge and skills needed to use the Git for version control of code and data. 
This is **not** a guide for version control for software developers and computer scientists, who may have more advanced needs.
It is meant to be an introduction to the goldstandard of version control for the scientific context, where version control is greatly underutilized in our opinion.
Whether you're conducting experiments, writing code, collaborating with peers, or managing complex datasets, Git provides a robust framework to enhance the efficiency, reproducibility, and collaboration of your work.

## Purpose

Version control can be a real game-changer for your scientific projects. 
By adopting Git, you gain the ability to trace the evolution of your work, experiment with new ideas without fear of irreversible consequences, and collaborate with a global community of researchers.
Of course using Git also adds some layer of complexity to your workflow.
We aim to simplify and demistify this complex tool for you.
Whether you're new to version control or have dabbled in it before, this book aims to be add something for all levels of expertise.

## How to use the book

This book takes a "code-first" approach.
Aiming to teach how to use the basics Git from the command line, without graphical interface tools.
We believe in learning by doing. 
Every concept introduced in this book is accompanied by practical examples and hands-on exercises.
Feel free to follow the exercises to gain the necassary "muscle-memory" to start using Git in your day-to-day work.

## Contribute

This book was created for the full-semester course: [Effective Progress Tracking and Collaboration: An Introduction to Version Control of Code and Data](https://lennartwittkuhn.com/version-control-course-uhh-ws23/) at [Universität Hamburg](https://www.uni-hamburg.de) 2023/24.
But the book is never finished, and your input can make it even better! 
If you spot typos, have suggestions for improvement, or want to contribute new content, we welcome your involvement!
If you find a typo, an unclear explanation, have an idea for a new chapter or want to see a specific topic covered you are more than welcome to open an issue or submit a pull request in the [GitHub repository](https://github.com/lnnrtwttkhn/version-control-book) of this book.
