### Initalize a Git repository

1. Create a folder called `recipes`.
1. Navigate to the `recipes` folder in your terminal.
1. Initialize a new Git repository in the `recipes` folder.

### Add content and commit changes

1. Create a new file called `recipes.txt`.
1. Add a *short* recipe to `recipes.txt` (any favorite or an intriguing AI-generated one).
1. Stage the new `recipes.txt` file.
1. Commit the changes in `recipes.txt` with a descriptive commit message.
1. :rocket: Optional: Commit at least three additional changes in `recipes.txt`.

### Amend a commit

1. Make additional changes to your `recipes.txt` file.
1. Stage the changes.
1. Amend the previous commit to include the new changes.

For example, add a recipe without a title first, commit, then add a title and amend the previous commit to add the title change to the same commit.

### Create a `.gitignore` file

1. Create a `.gitignore` file.
1. Create a random file that you want to ignore, for example `random-file.docx`.
1. Add the random file to the `.gitignore` file, stage and commit your changes.
1. Save, stage and commit the `.gitignore` file.
1. :rocket: All macOS users: Let your repository ignore `.DS_Store`.
