### "Public" collaboration with pull requests (using a fork and GitHub flow)

1. Find out what [forking](https://lennartwittkuhn.com/version-control-book/chapters/github-advanced.html) is
1. **Fork the repository** of another course participant (who is not your partner from the previous exercise)
1. Create an **issue**, suggesting a missing activity to do in Hamburg/Rotterdam
1. Repeat the steps from the previous exercise using the forked repository:
    1. **Clone** the *forked* repository into a sensible location on your computer
    1. **Create a new branch** and create **one or multiple commits** "fixing" the issue that you opened
    1. If available, follow the **contributing guide** of your partner's repository
    1. **Push** your changes to GitHub
    1. **Create a pull request** with your changes (hint: from the fork to the original repo) and refer to the issue in your pull request

### Review pull requests in your repository

1. View any pull requests that are created in your repository.
1. Review the changes made by the contributor in the pull request.
1. If needed, discuss additional changes with the contributor in the pull request.
1. Close the pull request by merging the proposed changes.

### Protect your branch

1. Go to your repository's "Settings" and select "Branches".
1. Under "Branch protection rules", click "Add rule" and enter "main" in the "Branch name pattern" field.
1. Enable the desired protection options (for example, require pull request reviews) and click "Create" to save the rule.
