### Initialize a Git repository

1. Navigate to the `recipes` folder in your terminal.
1. Initialize a new Git repository in the `recipes` folder.

### Add content and commit changes

3. Create a new file called `recipes.txt`.
4. Add a *short* recipe to `recipes.txt` (any favorite or an intriguing AI-generated one).
5. Stage the new `recipes.txt` file.
6. Commit the changes in `recipes.txt` with a descriptive commit message.

:rocket: Optional: Commit at least three additional changes in `recipes.txt`.

### Amend a commit

7. Make additional changes to your `recipes.txt` file.
8. Stage the changes.
9. Amend the previous commit to include the new changes.

For example, add a recipe without a title first, commit, then add a title and amend the previous commit to add the title change to the same commit.

### Create a `.gitignore` file

10. Create a random file that you want to ignore, for example `random-file.docx` or download an image from the internet.
11. Check the state of your repository to see that Git detects the untracked file.
11. Create a `.gitignore` file.
12. Add the random file to the `.gitignore` file so that it is ignored by Git and save the file.
13. Check the state of your repository again to see that Git does not list the file as untracked anymore.
14. Stage the changes in the `.gitignore` file.
15. Commit the changes in `.gitignore`.

:rocket: Optional (for macOS users): Let your repository ignore `.DS_Store`.
