---
title: "Installation and setup"
engine: knitr
execute:
  eval: false
  title-block-style: none
author: ""
---
::: callout-note
### Overview

{{< fa clock >}} Duration:  min
:::

# {{< fa bullseye >}} Objectives
- Download and configure Git

- Create a Github account

- Download and setup a text editor

## Cheatsheet

```{r}
#| eval: true
#| echo: false
#| message: false
#| warning: false
knitr::kable(table_cheatsheet(name = "config"), format = "markdown")
```

# {{< fa brands git-alt >}} Downloading Git

## {{< fa brands apple >}} macOS

### Option 1

::: {.callout-tip collapse="false"}
### Question: Where is the Terminal?

The Terminal can be found at `/Applications/Utilities/Terminal.app` or by searching the Spotlight for "Terminal".
You may want to keep Terminal in your dock to find it more easily.
:::

Open the terminal and type:

```{bash}
git --version
```

If git is not installed you will get a prompt asking you if you wish to install it along with Xcode command line tools.
You may be asked for your administrator password.

### Option 2

Download and run the installer from: [https://git-scm.com/download/mac](https://git-scm.com/download/mac).
Hit 'Continue' through the prompts without modifying the installation destination or other settings.
You may be asked for your administrator password.

### {{< fa brands linux >}} Linux

Check if you have git installed by opening your terminal and running:

```{bash}
git --version
```

If git is not installed, install it using your package manager, e.g., by running the following command in the terminal:

```{bash}
 sudo apt-get install git 
```

## {{< fa brands windows >}} Windows

Download the [Git for Windows installer](https://git-scm.com/download/win).
Hit 'Next' through the prompts without modifying the installation destination or other settings
Click [here](https://www.youtube.com/watch?v=-Bfx-v5mIDo) for a video tutorial.

# {{< fa brands github >}} Creating GitHub account

1.  Open <https://github.com> in your browser
2.  Click the `Sign up` button
3.  Enter the required personal details 
4.  In step 2 select the free plan.

::: {.callout-tip collapse="true"}
### Choosing a Github Name

Here are some tips for choosing a GitHub username:

```         
Incorporate your name.
Adapt your username from other platforms.
Choose a professional username for your future boss.
Opt for a shorter username.
Be unique and concise.
Avoid references to specific institutions.
Use all lowercase and hyphens for word separation.
```
:::

## GitHub Student Education Pack
The GitHub Student Developer Pack is a program offered by GitHub to students, providing them with free access to a collection of valuable developer tools and services. 
To benefit from the pack:
Visit the [**GitHub Education website**](https://www.education.github.com) and sign up with your student email to verify your academic status.
Once verified, you gain access to various resources, including GitHub Pro with unlimited private repositories, free domain names, cloud credits, coding courses, and more.

# {{< fa align-left >}} Downloading a Text Editor 

Sometimes, Git might ask you to write a commit message, and it can be annoying if you end up in an editor you don't like or don't know how to use.
The standard text editor is called **Vim**, which is widely known for being difficult to use. 
Therefore, it might be a smart move to consider switching to a different text editor. You can find more information about the challenges of using Vim (and some funny memes) [here](https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/).

Our Recommendation is [Nano](https://www.nano-editor.org/docs.php), which runs in the Terminal and is fairly easy to use.
However there are a lot of alternatives.


# Configuring Git
The git config command  is used to get and set configuration. 
It allows you to customize Git according to your preferences and requirements. 
To look at all the different Configuration commands you can use

```{bash}
git config
```
This chapter will only deal with the most important/necessary ones.

::: {.callout-tip title="What are the different configuration levels?" collapse="true"}
Git configuration values can be stored at three different levels:

**System-level Configuration**: This level applies configuration values to every user on the system and all their repositories.
To read or write configuration values at this level, you need administrative or superuser privileges.

**User-level Configuration**: This level is specific to an individual user. 
Configuration values set at this level will be applied to all repositories owned by the user.

**Repository-level Configuration**: This level is specific to a particular Git repository. 
The configuration values set at this level override values set at the system-level and user-level configurations for that specific repository. 
By default, Git reads from and writes to this file when you use the git config command without any additional options.
:::

## Identify yourself {{< fa person >}}

Before you start using Git, it's important to set your username and email address. 
This information is crucial because Git uses it to identify the author of each change you make. 
By associating your commits/changes with your username and email, it allows others to see who made the changes and facilitates collaboration within a project.

Setting your username and email is a one-time setup process, but you can always update them later if needed. 
To perform this configuration, you can use the Terminal.
It makes sense to use your Github account details. 

```{bash}

git config --global user.name "Example"
git config --global user.email beispiel@example.com

```

## Set Git editor {{< fa pen >}}

As mentioned earlier, you may come across various scenarios where you need to interact with text-based files, such as commit messages or merge conflict resolutions. 
Git relies on a text editor to allow you to make changes to these files within the Git workflow. 
To set your preferred text editor in Git, you can use the git config command

```{bash}

git config --global core.editor "editor name"

```

From now on, when Git requires you to interact with a text editor, it will use the one you have set.
If you ever want to change your Git editor in the future, you can repeat the above steps and specify the new editor command or path.

## Configure the default name for an initial branch {{< fa code-branch >}}

By default, Git uses the name "master" for the initial branch when creating a new repository.
However, there has been a growing movement to transition to using "main" as the default branch name instead.
One of the main motivations behind this change is to promote inclusivity and remove potentially offensive terminology from the default Git workflow. 
To configure the default branch name to "main" in Git, you can use the following command

```{bash}

git config --global init.defaultBranch main

```

## Check your Settings {{< fa gear >}}

You can check if your configurations worked using

```{bash}

git config --list

```

This should create an output similiar to this.

```{bash}

user.name=Example
user.email=beispiel@example.com
init.defaultbranch=main
core.editor=nano

```

Now that your Git environment is customized to your preferences, you are ready to utilize Git.

# Calling for Help {{< fa circle-question >}}

The **--help** option in Git is a command that provides you with access to the built-in Git documentation and help resources.
When you run a Git command followed by --help, Git displays information about that command, including its usage, available options, and a brief description of its functionality.

For example

```{bash}

git config --help

```

will open up a browser in the terminal containing information about the **config** command. To quit the browser use **q**.

While the command provides extensive documentation and information about Git commands, it is not the most beginner-friendly resource.

# {{< fa planet ringed >}} JupyterHub

In case the Installation process did not work on your device, you can access a remote environment using [**JupyterHub**](https://code.min.uni-hamburg.de)



# References 

https://happygitwithr.com/ 

https://swcarpentry.github.io/git-novice

/https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

https://www.youtube.com/watch?v=-Bfx-v5mIDo

